# Generated by Django 3.2 on 2023-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230418_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='Введите значение от 1 до 10', verbose_name='Рейтинг произведения'),
        ),
    ]
