# Generated by Django 3.2 on 2023-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
